name: ci
on:
  pull_request:
  push:
    branches:
    - master
  schedule:
  - cron: '00 01 * * *'
jobs:
  test:
    name: test
    env:
      # For some builds, we use cross to test on 32-bit and big-endian
      # systems.
      CARGO: cargo
      # When CARGO is set to CROSS, TARGET is set to `--target matrix.target`.
      TARGET:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build:
        - pinned
        - stable
        - stable-32
        - stable-mips
        - stable-arm
        - beta
        - nightly
        - macos
        - win-msvc
        - win-gnu
        include:
        - build: pinned
          os: ubuntu-18.04
          rust: 1.41.0
        - build: stable
          os: ubuntu-18.04
          rust: stable
        - build: stable-32
          os: ubuntu-18.04
          rust: stable
          target: i686-unknown-linux-gnu
        - build: stable-mips
          os: ubuntu-18.04
          rust: stable
          target: mips64-unknown-linux-gnuabi64
        - build: stable-arm
          os: ubuntu-18.04
          rust: stable
          # For stripping release binaries:
          # docker run --rm -v $PWD/target:/target:Z rustembedded/cross:arm-unknown-linux-gnueabihf arm-linux-gnueabihf-strip /target/arm-unknown-linux-gnueabihf/debug/rg
          target: arm-unknown-linux-gnueabihf
        - build: beta
          os: ubuntu-18.04
          rust: beta
        - build: nightly
          os: ubuntu-18.04
          rust: nightly
        - build: macos
          os: macos-latest
          rust: stable
        - build: win-msvc
          os: windows-2019
          rust: stable
        - build: win-gnu
          os: windows-2019
          rust: stable-x86_64-gnu
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        profile: minimal
        override: true

    - name: Use Cross
      if: matrix.target != ''
      run: |
        # FIXME: to work around bugs in latest cross release, install master.
        # See: https://github.com/rust-embedded/cross/issues/357
        cargo install --git https://github.com/rust-embedded/cross
        echo "::set-env name=CARGO::cross"
        echo "::set-env name=TARGET::--target ${{ matrix.target }}"

    - name: Show command used for Cargo
      run: |
        echo "cargo command is: ${{ env.CARGO }}"
        echo "target flag is: ${{ env.TARGET }}"

    - name: Build ripgrep and all crates
      run: ${{ env.CARGO }} build --verbose --all ${{ env.TARGET }}

    - name: Build ripgrep with PCRE2
      run: ${{ env.CARGO }} build --verbose --all --features pcre2 ${{ env.TARGET }}

    - name: Run tests with PCRE2 (sans cross)
      if: matrix.target == ''
      run: ${{ env.CARGO }} test --verbose --all --features pcre2 ${{ env.TARGET }}

    - name: Run tests without PCRE2 (with cross)
      if: matrix.target != ''
      run: ${{ env.CARGO }} test --verbose --all ${{ env.TARGET }}

    # Only worry about snappy-cpp when not using cross, since it's a pain
    # otherwise to deal with cross compiling with a C++ library. Similarly,
    # skip CPP testing on Windows.
    # - name: Install snappy C++ library (Ubuntu)
    #   if: env.CARGO == 'cargo' && matrix.os == 'ubuntu-18.04'
    #   run: sudo apt-get install libsnappy-dev

    # - name: Install snappy C++ library (macOS)
    #   if: env.CARGO == 'cargo' && matrix.os == 'macos-latest'
    #   run: brew install snappy

    # - name: Build snappy-cpp library
    #   if: env.CARGO == 'cargo' && matrix.os != 'windows-2019'
    #   run: cargo build --verbose --manifest-path snappy-cpp/Cargo.toml

    # - name: Run tests with snappy-cpp
    #   if: env.CARGO == 'cargo' && matrix.os != 'windows-2019'
    #   run: cargo test --verbose --manifest-path test/Cargo.toml --features cpp

    # - name: Compile benchmarks with snappy-cpp
    #   if: env.CARGO == 'cargo' && matrix.os != 'windows-2019'
    #   run: cargo bench --manifest-path bench/Cargo.toml --verbose --features cpp -- --test

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal
        components: rustfmt
    - name: Check formatting
      run: |
        cargo fmt --all -- --check
